import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
export  function Navbar(){

  return<div>
    <h1>WIKIGAME</h1>
    <label hidden="True">Modo administrador</label>
    <form>{/* Este formulario es para el buscador*/} 
      <select>
        <option>Tipo juego</option>
        <option>SandBox</option>
        <option>Shooter</option>
        <option>Lucha</option>
      </select>
      <input type="text" placeholder="Buscar"></input>
    </form>
    
    <button>Perfil</button>
  </div>
}
export  function Footer(){

  return<div>
   <p>Wikigame ©  2025- Contactos: fcorrom2907@g.educaand.es    - 999999999 - C/ Blanca de los rios 1</p>
  </div>
}
